linters:
  disable-all: true
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gosec
    - prealloc
    - nakedret
    - copyloopvar
    - gocritic
    - gocyclo
    - goimports
    - unparam
    - dogsled
    - bodyclose
    - goconst
    - gocognit
    - godox
    - funlen
    - whitespace
    - wsl
    - goprintffuncname
    - err113
    - godot
    - testpackage
    - nolintlint
    - asciicheck
    - exhaustive
    - mnd

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/felipepimentel/n8n-digitalocean-cicd
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  funlen:
    lines: 100
    statements: 50
  godox:
    keywords:
      - NOTE
      - TODO
      - OPTIMIZE
      - HACK
  whitespace:
    multi-if: false
    multi-func: false
  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-cuddle-declarations: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
  gocognit:
    min-complexity: 20
  godot:
    scope: declarations
    capital: false
  dogsled:
    max-blank-identifiers: 2
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
  err113:
    ignore-tests: true
  testpackage:
    skip-regexp: (export|internal)_test\.go
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-dirs:
    - vendor/
    - third_party/
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - staticcheck
        - err113
    - path: doc\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - staticcheck
        - err113

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 