name: Deploy n8n

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Required secrets
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  DO_SSH_KEY_FINGERPRINT: ${{ secrets.DO_SSH_KEY_FINGERPRINT }}
  DO_SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
  N8N_DOMAIN: ${{ secrets.N8N_DOMAIN }}
  N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}

  # Optional with defaults
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY || 'registry.digitalocean.com' }}
  DROPLET_NAME: ${{ secrets.DROPLET_NAME || 'n8n-server' }}
  N8N_VERSION: ${{ secrets.N8N_VERSION || 'latest' }}
  N8N_BASIC_AUTH_USER: ${{ secrets.N8N_BASIC_AUTH_USER || 'admin' }}
  N8N_BASIC_AUTH_PASSWORD: ${{ secrets.N8N_BASIC_AUTH_PASSWORD || secrets.N8N_ENCRYPTION_KEY }}
  DO_SSH_KEY_PATH: ${{ secrets.DO_SSH_KEY_PATH || '~/.ssh/id_rsa' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          cd ci
          go mod download

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H digitalocean.com >> ~/.ssh/known_hosts
          ssh-keyscan -H registry.digitalocean.com >> ~/.ssh/known_hosts

      - name: Deploy n8n
        run: |
          cd ci
          go run main.go
